# Generated by Django 3.2.4 on 2021-06-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbdinf', '0002_auto_20210619_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
